name: Docker Image CI

on:
  schedule:
   - cron: '0 22 * * *'
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_TOKEN}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag resimon/gitlab_sendmail:latest
    - name: publish docker image
      run: docker push ${{secrets.DOCKER_USER}}/gitlab_sendmail:latest
